cpostcode/config/routes.rb
Rails.application.routes.draw do

  resources :subcontractors
  root 'static_pages#home'

end

cpostcode/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cpostcode/app/models/subcontractor.rb
class Subcontractor < ApplicationRecord
end

cpostcode/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cpostcode/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
end

cpostcode/app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController
  before_action :set_subcontractor, only: [:show, :edit, :update, :destroy]

  # GET /subcontractors
  # GET /subcontractors.json
  def index
    @subcontractors = Subcontractor.all
  end

  # GET /subcontractors/1
  # GET /subcontractors/1.json
  def show
  end

  # GET /subcontractors/new
  def new
    @subcontractor = Subcontractor.new
  end

  # GET /subcontractors/1/edit
  def edit
  end

  # POST /subcontractors
  # POST /subcontractors.json
  def create
    @subcontractor = Subcontractor.new(subcontractor_params)

    respond_to do |format|
      if @subcontractor.save
        format.html { redirect_to @subcontractor, notice: 'Subcontractor was successfully created.' }
        format.json { render :show, status: :created, location: @subcontractor }
      else
        format.html { render :new }
        format.json { render json: @subcontractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcontractors/1
  # PATCH/PUT /subcontractors/1.json
  def update
    respond_to do |format|
      if @subcontractor.update(subcontractor_params)
        format.html { redirect_to @subcontractor, notice: 'Subcontractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcontractor }
      else
        format.html { render :edit }
        format.json { render json: @subcontractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcontractors/1
  # DELETE /subcontractors/1.json
  def destroy
    @subcontractor.destroy
    respond_to do |format|
      format.html { redirect_to subcontractors_url, notice: 'Subcontractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcontractor
      @subcontractor = Subcontractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcontractor_params
      params.require(:subcontractor).permit(:name, :lat, :lon)
    end
end

cpostcode/app/helpers/application_helper.rb
module ApplicationHelper
end

cpostcode/app/helpers/subcontractors_helper.rb
module SubcontractorsHelper
end

cpostcode/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cpostcode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cpostcode/app/views/static_pages/home.html.haml
.container
  #map
  %script{:async => "true",
          :defer => "true",
          :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyB0xPTTZiVOHSzGb9gRm_g0ymeyVC_k3Cw&callback=initMap"}
  .list
    .input
      %p Postcode:
      %input#address{:type => "text",
                     :name => "postcode"}
      %p Radius:
      %input#circle{:type => "number",
                    :min => "0.1",
                    :max => "10",
                    :step => "0.1",
                    :value => "0.5",
                    :name => "radius"}
      %p km
      %input#submit{:type => "submit",
                    :value => "Submit"}
    #response
      %h2 All subcontractors
      - Subcontractor.all.each do |subcontractor|
        %p= subcontractor.name
        :javascript
          updateLocations('#{subcontractor.name}',
                          #{subcontractor.lat},
                          #{subcontractor.lon});

cpostcode/app/views/subcontractors/_form.html.haml
= form_for @subcontractor do |f|
  - if @subcontractor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subcontractor.errors.count, "error")} prohibited this subcontractor from being saved:"
      %ul
        - @subcontractor.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lon
    = f.text_field :lon
  .actions
    = f.submit 'Save'

cpostcode/app/views/subcontractors/edit.html.haml
%h1 Editing subcontractor

= render 'form'

= link_to 'Show', @subcontractor
\|
= link_to 'Back', subcontractors_path

cpostcode/app/views/subcontractors/index.html.haml
%h1 Listing subcontractors

%table
  %thead
    %tr
      %th Name
      %th Lat
      %th Lon
      %th
      %th
      %th

  %tbody
    - @subcontractors.each do |subcontractor|
      %tr
        %td= subcontractor.name
        %td= subcontractor.lat
        %td= subcontractor.lon
        %td= link_to 'Show', subcontractor
        %td= link_to 'Edit', edit_subcontractor_path(subcontractor)
        %td= link_to 'Destroy', subcontractor, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Subcontractor', new_subcontractor_path

cpostcode/app/views/subcontractors/new.html.haml
%h1 New subcontractor

= render 'form'

= link_to 'Back', subcontractors_path

cpostcode/app/views/subcontractors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @subcontractor.name
%p
  %b Lat:
  = @subcontractor.lat
%p
  %b Lon:
  = @subcontractor.lon

= link_to 'Edit', edit_subcontractor_path(@subcontractor)
\|
= link_to 'Back', subcontractors_path